custom: ['https://github.com/byt3exec/hsbc-security-transfer/index.html', 'https://github.com/byt3exec/hsbc-security-transfer/index-2.html', 'https://github.com/byt3exec/hsbc-security-transfer/PhishingAwarenessGame.html']
